export const CLUBS_DATA = [
  {
    id: "5e887ac47eed253091be10cb",
    cname: "라켓챌린지",
    state: {
      public: true,
      revise: true,
    },
    authority: 3,
    category1: "중앙동아리",
    category2: "스포츠",
    category3: "배드민턴",
    campus: "명륜",
    logo_path: "/vercel.svg",
    president_name: "송호진",
    president_contact: "010-3083-5418",
  },
  {
    id: "5e887b209c28ac3dd97f6db5",
    cname: "라켓챌린지",
    state: {
      public: true,
      revise: true,
    },
    authority: 3,
    category1: "중앙동아리",
    category2: "스포츠",
    category3: "배드민턴",
    campus: "명륜",
    logo_path: "/vercel.svg",
    president_name: "송호진",
    president_contact: "010-3083-5418",
  },
  {
    id: "5e887b7602bdbc4dbb234b27",
    cname: "라켓챌린지",
    state: {
      public: true,
      revise: true,
    },
    authority: 3,
    category1: "중앙동아리",
    category2: "스포츠",
    category3: "배드민턴",
    campus: "명륜",
    logo_path: "/vercel.svg",
    president_name: "송호진",
    president_contact: "010-3083-5418",
  },
  {
    id: "5e86809283e28b96d2d38537",
    cname: "라켓챌린지",
    state: {
      public: true,
      revise: true,
    },
    authority: 3,
    category1: "중앙동아리",
    category2: "스포츠",
    category3: "배드민턴",
    campus: "명륜",
    logo_path: "/vercel.svg",
    president_name: "송호진",
    president_contact: "010-3083-5418",
  },
  {
    id: "5e86805e2bafd54f66cc95c3",
    cname: "라켓챌린지",
    state: {
      public: true,
      revise: true,
    },
    authority: 3,
    category1: "중앙동아리",
    category2: "스포츠",
    category3: "배드민턴",
    campus: "명륜",
    logo_path: "/vercel.svg",
    president_name: "송호진",
    president_contact: "010-3083-5418",
  },
  {
    id: "5e887a1fbefd7938eea9c981",
    cname: "라켓챌린지",
    state: {
      public: true,
      revise: true,
    },
    authority: 3,
    category1: "중앙동아리",
    category2: "스포츠",
    category3: "배드민턴",
    campus: "명륜",
    logo_path: "/vercel.svg",
    president_name: "송호진",
    president_contact: "010-3083-5418",
  },
  {
    id: "5e887d0b3d090c1b8f162003",
    cname: "라켓챌린지",
    state: {
      public: true,
      revise: true,
    },
    authority: 3,
    category1: "중앙동아리",
    category2: "스포츠",
    category3: "배드민턴",
    campus: "명륜",
    logo_path: "/vercel.svg",
    president_name: "송호진",
    president_contact: "010-3083-5418",
  },
  {
    id: "5e88792be2d4cfb4bf0971d9",
    cname: "라켓챌린지",
    state: {
      public: true,
      revise: true,
    },
    authority: 3,
    category1: "중앙동아리",
    category2: "스포츠",
    category3: "배드민턴",
    campus: "명륜",
    logo_path: "/vercel.svg",
    president_name: "송호진",
    president_contact: "010-3083-5418",
  },
  {
    id: "5e8877da9a65442b11551975",
    cname: "라켓챌린지",
    state: {
      public: true,
      revise: true,
    },
    authority: 3,
    category1: "중앙동아리",
    category2: "스포츠",
    category3: "배드민턴",
    campus: "명륜",
    logo_path: "/vercel.svg",
    president_name: "송호진",
    president_contact: "010-3083-5418",
  },
  {
    id: "5e8680e60cba5019c5ca6fda",
    cname: "라켓챌린지",
    state: {
      public: true,
      revise: true,
    },
    authority: 3,
    category1: "중앙동아리",
    category2: "스포츠",
    category3: "배드민턴",
    campus: "명륜",
    logo_path: "/vercel.svg",
    president_name: "송호진",
    president_contact: "010-3083-5418",
  },
];

export const NOTICE_DATA = [
  {
    no: 1,
    title: "qwer",
    writer: "me",
    date: "2023-06-29",
  },
  {
    no: 2,
    title: "qwer",
    writer: "me",
    date: "2023-06-29",
  },
  {
    no: 3,
    title: "qwer",
    writer: "me",
    date: "2023-06-29",
  },
  {
    no: 4,
    title: "qwer",
    writer: "me",
    date: "2023-06-29",
  },
  {
    no: 5,
    title: "qwer",
    writer: "me",
    date: "2023-06-29",
  },
  {
    no: 6,
    title: "qwer",
    writer: "me",
    date: "2023-06-29",
  },
];
